name: Stale Pull Request Check

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8 * * *'

jobs:
  check_stale_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for multiple stale pull requests
      id: check_prs
      run: |
        DATE_CREATED=$(date -d '4 hours ago' --utc +%Y-%m-%dT%H:%M:%SZ)
        PR_JSON=$(gh pr list --repo ${{ github.repository }} --state open --json createdAt,url,title -q ".[] | select(.createdAt < \"$DATE_CREATED\") | .url")

        PR_COUNT=$(echo "$PR_JSON" | wc -l)

        echo "TOTAL_PR_COUNT=$PR_COUNT" >> $GITHUB_ENV

        if [[ -n "$PR_JSON" ]]; then
          PR_ATTACHMENTS=""
          while read -r pr; do
            PR_ATTACHMENTS="$PR_ATTACHMENTS,{\"title\": \"Pull Request\",\"value\": \"$pr\",\"short\": false}"
          done <<< "$PR_JSON"
          
          echo "HAS_STALE_PRS=true" >> $GITHUB_ENV
          echo "PR_ATTACHMENTS=${PR_ATTACHMENTS:1}" >> $GITHUB_ENV
        else
          echo "No stale pull request found."
          echo "HAS_STALE_PRS=false" >> $GITHUB_ENV
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Send stale pull request notification to Slack
      if: env.HAS_STALE_PRS == 'true'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message
        custom_payload: |
          {
            "text": "${{ env.TOTAL_PR_COUNT }} stale pull request(s) found!",
            "attachments": [
              {
                "color": "#FF0000",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  ${{ env.PR_ATTACHMENTS }}
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}