name: Get Slack and GitHub Usernames

on:
  workflow_dispatch:

jobs:
  get-slack-usernames:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - run: python3 -m pip install -r python/requirements.txt
        - run: python3 -m python.scripts.get_github_and_slack_usernames
          env:
            ADMIN_GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT_TOKEN }}
            ADMIN_SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            METADATA_API_URL: ${{ secrets.METADATA_API_URL }}
            METADATA_API_TOKEN: ${{ secrets.METADATA_API_TOKEN }}
